name: test the thingy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-job:

    runs-on: ubuntu-latest

    steps:
      - name: testiiing
        run: |
          pwd
          chmod +x ../../du1/tester/testall.sh
          ../../du1/tester/testall.sh
