name: test the thingy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-job:

    runs-on: ubuntu-latest

    steps:
      - name: testiiing
        run: |
          chmod +x /./du1/tester/runtest.sh
          /./du1/tester/runtest.sh
